DROP TABLE IF EXISTS answers CASCADE;

CREATE TABLE answers(
  id SERIAL PRIMARY KEY NOT NULL,
  question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  answers TEXT NOT NULL,
  is_right BOOLEAN NOT NULL DEFAULT FALSE
);